# Generated by Django 3.2.7 on 2022-04-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spaceShip_name', models.CharField(max_length=50)),
                ('spaceShip_weight', models.FloatField()),
                ('country_made', models.CharField(max_length=50)),
                ('launch_date', models.DateTimeField()),
                ('num_of_payloads', models.IntegerField()),
            ],
        ),
    ]
